dist: bionic
language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - libarmadillo-dev
      - libeigen3-dev
      - libopenblas-dev
      - libsuitesparse-dev
      - libglew-dev
      - freeglut3-dev
      - libgles2-mesa-dev
      - cimg-dev
      - libcgal-dev
  snaps:
    - name: cmake
      confinement: classic
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - $CC -v && $CXX -v && cmake --version
  - mkdir build && cd build
  - cmake ..

