language: cpp
matrix:
  include:
    - name: "Ubuntu 19.10"
      os: linux
      dist: bionic
      group: travis_latest
      env: DOCKER="ubuntu:eoan" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - name: "Ubuntu 19.04"
      os: linux
      dist: bionic
      group: travis_latest
      env: DOCKER="ubuntu:disco" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
    - name: "Ubuntu 18.04"
      os: linux
      dist: bionic
      group: travis_latest
      env: DOCKER="ubuntu:bionic" VARIANT="ubuntu" TOOL="compile" COMPILER_C="gcc" COMPILER_CXX="g++"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - libarmadillo-dev
      - libeigen3-dev
      - libopenblas-dev
      - libsuitesparse-dev
      - libsuitesparseconfig5
      - libglew-dev
      - freeglut3-dev
      - libgles2-mesa-dev
      - cimg-dev
      - libcgal-dev
script:
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - $CC -v && $CXX -v && cmake --version
  - mkdir build && cd build
  - cmake ..

